//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by script.rc
//
#define IDOK2                           2
#define IDC_MESSAGE                     1000
#define IDC_TEXT_ABOUTTITLE             1001
#define IDC_NAME                        1002
#define IDC_COMBO_CHANNEL               1002
#define IDC_VERSION                     1003
#define IDC_COMBO_BPS                   1003
#define IDC_COMBO_SPS                   1004
#define IDC_TEXT_FREQUENCY              1004
#define IDC_FREQUENCY_MAIN              1005
#define IDC_TEXT_HERTZ                  1006
#define IDC_VOLUME_MAIN                 1007
#define IDC_TEXT_FREQUENCY2             1008
#define IDC_TEXT_HERTZ2                 1009
#define IDC_CHANNEL_OFFSET              1009
#define IDC_CHANNELOFFSET               1009
#define IDC_WAITSAMPLE                  1009
#define IDC_OFFSET                      1010
#define IDC_OFFSET_MAIN                 1010
#define IDC_TEXT_FREQUENCY3             1011
#define IDC_TEXT_HERTZ3                 1012
#define IDC_TEXT_CHANNELOFFSET          1012
#define IDC_TEXT_WAITSAMPLE             1012
#define IDC_COMBO_TYPE_MAIN             1013
#define IDC_TEXT_FREQUENCY4             1014
#define IDC_TEXT_REVERSE                1015
#define IDC_CHECK_REVERSE_MAIN          1016
#define IDC_SAMPLESIZE                  1017
#define IDC_CHECK_REVERSE_FREQ          1017
#define IDC_SEC                         1018
#define IDC_SAMPLENUM                   1019
#define IDC_CHECK_REVERSE_MAIN3         1020
#define IDC_CHECK_REVERSE_VOLUME        1020
#define IDC_CHECK_ENABLE                1021
#define IDC_ENVELOPE_SEC_1              1022
#define IDC_ENVELOPE_SEC_2              1023
#define IDC_TAB4                        1024
#define IDC_TAB                         1024
#define IDC_ENVELOPE_SEC_3              1025
#define IDC_SEC2                        1026
#define IDC_QUALITY                     1026
#define IDC_TEXT_PAN                    1027
#define IDC_ENVELOPE_SEC_4              1028
#define IDC_UNITNO                      1030
#define IDC_X                           1031
#define IDC_CHECK_RIGHT                 1032
//#define IDC_IMAGEINDEX                  1032
#define IDC_CHECK_RIGHT2                1033
#define IDC_CHECK_BOTTOM                1033
//#define IDC_COMBO_DIR                   1033
//#define IDC_EVENTNAME                   1034
//#define IDC_EVENTNAME_1                 1034
//#define IDC_COMBO_DIR2                  1035
#define IDC_COMBO_UNIT                  1035
#define IDC_COMBO_TYPE                  1035
//#define IDC_EVENTNAME2                  1036
//#define IDC_EVENTNAME_2                 1036
#define IDC_FREQUENCY_FREQ              1037
#define IDC_COMBO_DIR3                  1037
#define IDC_COMBO_FLAGNO                1037
#define IDC_STAGE_NAME                  1037
#define IDC_TEXT_NAME                   1038
#define IDC_TEXT_HERTZ4                 1038
#define IDC_VOLUME_FREQ                 1039
#define IDC_IMAGEINDEX3                 1039
#define IDC_PARAM2                      1039
#define IDC_TEXT_HERTZ5                 1040
#define IDC_TEXT_SPS                    1041
#define IDC_OFFSET_FREQ                 1041
#define IDC_TEXT_LANGE                  1042
#define IDC_TEXT_LENGTH                 1042
#define IDC_TEXT_HERTZ6                 1042
#define IDC_FLAGNO                      1042
#define IDC_TEXT_SEC                    1043
#define IDC_COMBO_TYPE_FREQ             1043
#define IDC_ANC_N_ROOMNO                1043
#define IDC_FREQUENCY_VOLUME            1044
#define IDC_ANC_S_ROOMNO                1044
#define IDC_TEXT_HERTZ7                 1045
#define IDC_ANC_N_X                     1045
#define IDC_VOLUME_VOLUME               1046
#define IDC_ANC_S_X                     1046
#define IDC_TEXT_HERTZ8                 1047
#define IDC_ANC_N_Y                     1047
#define IDC_OFFSET_VOLUME               1048
#define IDC_ANC_S_Y                     1048
#define IDC_TEXT_HERTZ9                 1049
#define IDC_RADIO_N                     1049
#define IDC_COMBO_TYPE_VOLUME           1050
#define IDC_RADIO_S                     1050
#define IDC_ENVELOPE_VOL_1              1051
#define IDC_CHECK_JUMP                  1051
#define IDC_ENVELOPE_VOL_2              1052
#define IDC_DOORNO                      1052
#define IDC_TEXT_SAMPLENUM              1053
#define IDC_ANC_N_AREANO                1053
#define IDC_TEXT_SEC2                   1054
#define IDC_ANC_S_ROOMNO2               1054
#define IDC_ANC_S_AREANO                1054
#define IDC_ROOM_NAME                   1054
#define IDC_ENVELOPE_VOL_3              1055
#define IDC_ENEMY_GROUP_0               1055
#define IDC_TEXT_INITIALIZETITLE        1056
#define IDC_TEXT_QUALITYTITLE           1056
#define IDC_PAN                         1056
#define IDC_ENEMY_GROUP_1               1057
#define IDC_CMB_N_ROOM                  1057
#define IDC_ENEMY_GROUP_2               1058
#define IDC_CMB_N_AREA                  1058
#define IDC_TEXT_WAVETITLE              1059
#define IDC_TEXT_UNITTITLE              1059
#define IDC_ENEMY_GROUP_3               1059
#define IDC_CMB_S_ROOM                  1059
#define IDC_ENEMY_GROUP_4               1060
#define IDC_CMB_S_AREA                  1060
#define IDC_TEXT_SURETITLE              1061
#define IDC_ENCOUNTER                   1061
#define IDC_TEXT_TOTALSAMPLE            1062
//#define IDC_COMBO1                      1062
#define IDC_COMBO_AREANO                1062
#define IDC_CREATOR                     1075
#define IDC_BASICKEY                    1076
#define IDC_TEXT_BASICKEY               1081
#define IDC_TEXT_HEARSELECT             1083
#define IDC_LIST                        1084
#define IDC_DIRECTORYPATH               1085
#define IDC_INFORMATION                 1086
#define IDC_CHECK_SOUND                 1087
#define IDC_TEXT_CONFIGTITLE            1102
#define IDC_TEXT_BUILD_QUALITY          1103
#define IDC_TEXT_BUILD_CHANNEL          1104
#define IDC_TEXT_BUILD_BPS              1105
#define IDC_TEXT_BUILD_SPS              1106
#define IDC_COMBO_BUILD_CHANNEL         1107
#define IDC_COMBO_BUILD_BPS             1108
#define IDC_COMBO_BUILD_SPS             1109
#define IDC_TEXT_AT_QUALITY             1110
#define IDC_TEXT_AT_CHANNEL             1111
#define IDC_TEXT_AT_BPS                 1112
#define IDC_TEXT_AT_SPS                 1113
#define IDC_COMBO_AT_CHANNEL            1114
#define IDC_COMBO_AT_BPS                1115
#define IDC_COMBO_AT_SPS                1116
#define IDC_TEXT_AT_BUFFER              1117
#define IDC_AT_BUFFER                   1118
#define IDC_WIDTH                       1118
#define IDC_TEXT_SECOND                 1119
#define IDC_HEIGHT                      1119
#define IDC_COMBO_AT_DEVICE             1120
#define IDC_Y                           1120
#define IDC_TEXT_AT_DEVICE              1121
#define IDC_Y2                          1121
#define IDC_EXTRA                       1121
#define IDC_DEFAULT                     1122
#define IDC_BASICKEY_UP                 1123
#define IDC_BASICKEY_DOWN               1124
#define IDC_SAVE_AS                     1125
#define IDC_SAVE                        1126
#define IDC_LOAD                        1127
#define IDC_LOAD2                       1128
#define IDC_SAVE_AS2                    1128
#define IDC_QUALITY_DIALOG              1129
#define IDM_CLOSE                       40002
#define IDM_CONFIG                      40010
#define IDM_VOLUMEDIALOG                40011
#define IDM_PROPERTY                    40012
#define IDM_ABOUT                       40013
#define IDM_OUTPUT_PTVOICE              40014
#define IDM_EXPORT_VOICE                40017
#define IDM_INPORT_VOICE                40018
#define IDM_UNIT                        40024
#define IDM_INITIALIZE                  40026
#define IDM_NEW_PCM                     40034
#define IDM_EDIT_PCM                    40035
#define IDM_PCM_QUALITY                 40037
#define IDM_PCM_EDIT                    40038
#define IDM_MAPSIZE                     40044
#define IDM_CLEAR_PXMAP                 40045
#define IDM_SAVE_STGPRJ                 40054
#define IDM_SAVE_STGPRJ_AS              40055
#define IDM_SORTEVENT_UP                40064
#define IDM_ATTRIBUTESIZE               40077
#define IDM_MODE_MAP2                   40079
#define IDM_MODE_MAP3                   40080
#define IDM_VIEW_LAYER_ONE              40083
#define IDM_VIEW_LAYER_ALL              40085
#define IDM_MODE_ATT1                   40086
#define IDM_MODE_ATT2                   40088
#define IDM_MODE_MAPALL                 40090
#define IDM_MODE_RESIDENT               40093
#define IDM_RECORD_ADD                  40094
#define IDM_RECORD_EDIT                 40095
#define IDM_RECORD_DELETE               40096
#define IDM_STAGE_NEW                   40098
#define IDM_STAGE_LOAD                  40099
#define IDM_MAP_NEW                     40100
#define IDM_STAGE_SAVE                  40102
#define IDM_MODE_MAP                    40103
#define IDM_MODE_FIELDUNIT              40105
#define IDM_MODE_FIELDDOOR              40107
#define IDM_ROOM                        40109

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         40110
#define _APS_NEXT_CONTROL_VALUE         1063
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
